server: 
  port: 3000

executor:
  corePoolSize: 200
  maxPoolSize: 200
  queueCapacity: 1800

scheduler:
  poolSize: 200

cron:
  schedule: 0 0/2 * * * ?

dryRun: false

default:
  probability: 0.1
  
openstack:
  username: admin
  password: datalyse
  projectID: ecd02933c4244991b83e5a86c0279645
  domainName: Default
  endpoint: http://193.51.236.63/identity/v3
ssh:
  user: ubuntu
  key: /home/magg/.ssh/cloud.key
  
redis:
  hostname: localhost
  port: 6379
  password: foobared
  
spring:
  main:
    banner-mode: off
    
security:
  user:
    name: magg
    password: 78fa095d-3f4c-48b1-ad50-e24c31d5cf69
       
failure:
 modes:
   shutdowninstance: true
   blockallnetworktraffic: false 
   
  