server: 
  port: 3000

executor:
  corePoolSize: 200
  maxPoolSize: 200
  queueCapacity: 1800

scheduler:
  poolSize: 200

cron:
  schedule: 0 0/2 * * * ?

dryRun: false

default:
  probability: 0.9
  
openstack:
  username: admin
  password: datalyse
  projectID: b646566024fe4fde81e9b48cb6377ab0
  domainName: Default
  endpoint: http://193.51.236.246/identity/v3
ssh:
  user: ubuntu
  key: /home/magg/.ssh/cloud.key
  
redis:
  hostname: localhost
  port: 6379
  password: foobared
  