server: 
  port: 3000

executor:
  corePoolSize: 200
  maxPoolSize: 200
  queueCapacity: 1800

scheduler:
  poolSize: 200

schedule: 0 0/1 * * * ?

dryRun: true
  
openstack:
  username: admin
  password: datalyse
  projectID: 68db99280ac44db0976b0249d02bcb80
  domainName: Default
  endpoint: http://193.51.236.246/identity/v3
ssh:
  user: ubuntu
  key: /home/magg/.ssh/cloud.key