server: 
  port: 3000

executor:
  corePoolSize: 200
  maxPoolSize: 200
  queueCapacity: 1800

scheduler:
  poolSize: 200

cron:
  schedule: 0 0/10 * * * ?

dryRun: false

default:
  probability: 0.2
  
openstack:
  username: admin
  password: datalyse
  projectID: ecd02933c4244991b83e5a86c0279645
  domainName: Default
  endpoint: http://193.51.236.63/identity/v3
ssh:
  user: ubuntu
  key: /home/magg/.ssh/cloud.key
  
redis:
  hostname: localhost
  port: 6379
  password: foobared
  
spring:
  main:
    banner-mode: off
  